<a href="https://colab.research.google.com/github/RuleOfNight/NumPy/blob/main/Untitled0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np

#Ép kiểu của list thành array
list = [[1,2,3]]
a = np.array(list)
print(a)
a = np.array([1,2,3])
print(a)

[[1 2 3]]
[1 2 3]


In [8]:
#Đếm số chiều của mảng
a.ndim
print(a.ndim)
b = np.array([[1,2,3],[4,5,6]])
print(b.ndim)

1
2


In [10]:
#Đếm số hàng và cột
a.shape
list = [
    [1,2,3],
    [4,5,6],
    [7,8,9]
]
a = np.array(list)
print(a.shape)

(3, 3)


In [14]:
#Tạo 1 ma trận chỉ toàn 0
a = np.zeros((4,5))
print(a)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [16]:
#Tạo 1 ma trận chỉ toàn 1
a = np.ones((6,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [17]:
#Định dạng kiểu dữ liệu
a.dtype
a = np.zeros((5,5), dtype='int32')
print(a)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [64]:
import random
row = col = 4
list = []


for i in range(0,row+1):
  row = []
  for element in range(0,col+1):
    row.append(random.randrange(0,101))
  list.append(row)

a = np.array(list)

for i in list:
  for j in i:
    print('{:<5}'.format(j), end='')
  print()

12   4    78   52   62   
38   42   94   68   16   
98   30   76   44   64   
40   35   14   44   49   
9    36   30   2    37   


In [54]:
#Lấy kích cỡ mảng
print(a.itemsize)

8


In [56]:
#Lấy số lượng ptu có trong mảng
print(a.size)

25


In [73]:
#In ra giá trị tại 1 vị trí cụ thể
print(a[1][1])
print(a[4,2])
#Chọn cả 1 vùng
print(a[:,1])
print(a[4,:])

print(a[1:-1,2:-2])

42
30
[ 4 42 30 35 36]
[ 9 36 30  2 37]
[[94]
 [76]
 [14]]


In [75]:
#Tạo 1 ma trận toàn số tự chọn
num =10
np.full((2,2),num)

array([[10, 10],
       [10, 10]])

In [76]:
#Tạo ma trận đơn vị
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [77]:
#Tính toán ma trận cơ bản
a = np.array([1,2,3,4])
print(a)
print(a+2)
print(a-2)
print(a*2)
print(a/2)

[1 2 3 4]
[3 4 5 6]
[-1  0  1  2]
[2 4 6 8]
[0.5 1.  1.5 2. ]


In [78]:
#Lượng giác và các cthuc khác
print(np.cos(a))
print(np.sin(a))
print(np.tan(a))
print(np.sqrt(a))
print(np.log(a))
print(np.exp(a))


[ 0.54030231 -0.41614684 -0.9899925  -0.65364362]
[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
[ 1.55740772 -2.18503986 -0.14254654  1.15782128]
[1.         1.41421356 1.73205081 2.        ]
[0.         0.69314718 1.09861229 1.38629436]
[ 2.71828183  7.3890561  20.08553692 54.59815003]
