<a href="https://colab.research.google.com/github/RuleOfNight/NumPy/blob/main/Linear%20Algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import random

# **Linear Algebra -  Đại số tuyến tính**

In [14]:
matrix_A = np.random.randint(0,100,size=(3, 4))

print(matrix_A)

matrix_B = np.random.randint(0,100,size=(4, 3))

print(matrix_B)

print(np.matmul(matrix_A,matrix_B))

[[24 63 69 34]
 [60 86 15 66]
 [41  8 75 48]]
[[31 58 97]
 [55 57 13]
 [35 16 91]
 [11 27 42]]
[[ 6998  7005 10854]
 [ 7841 10404 11075]
 [ 4864  5330 12922]]


In [22]:
#Tính định thức của ma trận
matrix_A = np.random.randint(0,100,size=(3, 3))

print(matrix_A)
print()
print(int(np.linalg.det(matrix_A)))


[[82  0 89]
 [10 40 88]
 [84 90 92]]

-566619


In [29]:
#Tính ma trận nghịch đảo
matrix_A = np.random.randint(0,100,size=(3, 3))

print(matrix_A)
print()
print((np.linalg.inv(matrix_A)))

[[88 17 30]
 [45 70 98]
 [83 85 84]]

[[ 0.01218106 -0.00557843  0.00215779]
 [-0.02164748 -0.02437205  0.0361653 ]
 [ 0.00986914  0.03017421 -0.02682318]]


In [31]:
#Tính hạng của ma trận(rank)
matrix_A = np.random.randint(0,100,size=(3, 3))

print(matrix_A)
print()
print(int(np.linalg.matrix_rank(matrix_A)))

[[73 21  6]
 [ 9 90 47]
 [56 40 36]]

3


In [36]:
#Lấy giá trị lớn/nhỏ nhất trong ma trận
matrix_A = np.random.randint(0,100,size=(3, 3))

print(matrix_A)
print()
print(np.max(matrix_A))
print(np.min(matrix_A))
#Tìm trong từng hàng/cột cụ thể
print(np.max(matrix_A,axis=0))
print(np.max(matrix_A,axis=1))

[[20 36 25]
 [81 87 33]
 [10 46 21]]

87
10
[81 87 33]
[36 87 46]


In [39]:
#Tính tổng tất cả phần tử trong cả ma trận hoặc từng hàng cụ thể
matrix_A = np.random.randint(0,100,size=(3, 3))

print(matrix_A)
print()
print(np.sum(matrix_A))
print()
print(np.sum(matrix_A,axis=0))

[[57 25 25]
 [65 34 27]
 [88 72 63]]

456

[210 131 115]


In [41]:
#Sửa đổi số hàng và cột trong ma trận
matrix_A = np.random.randint(0,100,size=(3, 3))

print(matrix_A)
print()
print(np.reshape(matrix_A,(1,9)))
#Lưu ý, số hàng và cột mới phải thỏa mãn số lượng phần tử có trong ma trận

[[16 66 80]
 [69 67 38]
 [34 85 79]]

[[16 66 80 69 67 38 34 85 79]]


In [47]:
#Stack
a = np.random.randint(0,100,size=(1, 3))
b = np.random.randint(0,100,size=(1, 3))

print(np.vstack((a,b)))
print()
print(np.vstack((b,a)))
print()
np.vsplit(np.vstack((a,b)),2)

print(np.hstack((a,b)))
print()
print(np.hstack((b,a)))
print()
np.hsplit(np.hstack((a,b)),2)

[[94  8 55]
 [ 9 53 40]]

[[ 9 53 40]
 [94  8 55]]

[[94  8 55  9 53 40]]

[[ 9 53 40 94  8 55]]



[array([[94,  8, 55]]), array([[ 9, 53, 40]])]

# **Ứng dụng xử lí ra vào File**

In [52]:
#Lấy dữ liệu từ file
data = np.genfromtxt('data.txt',delimiter=',', dtype='int32')
print(data)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8]]


In [60]:
#Kiểm tra điều kiện của data
data >50
print(~(data > 50)) #Dấu ~ để căn phần tử
print()
data[data > 50]
print(data[data %2 == 0]) #Chỉ in ra các giá trị thỏa mãn

[[ True  True  True  True False False  True  True  True  True  True  True
   True  True]
 [ True  True  True  True False False  True False  True  True  True  True
   True  True]
 [ True  True  True  True False  True  True  True False  True  True  True
   True  True]]

[196   4  34   6   8   0  42  12 766   4   6   4   4   6  22   2  78   0
   2   8]
